name: CI
on:
  push:
    branches: ping-main
# Environment variables must be single quote delimitted; other scripts read out of this file (very cursed) and expect it.
env:
  DEPS_VERSION_WIN: '2022-03-16'
  VLC_VERSION_WIN: '3.0.0-git'
  CEF_BUILD_VERSION_WIN: '4638'
  CMAKE_GENERATOR: 'Visual Studio 17 2022'
  VIRTUALCAM-GUID: '1B4706D6-9902-454A-8345-32F305BCFD28'
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        run: CI/build-windows.ps1 -CombinedArchs -Package
      - name: Find artifacts
        id: artifactName
        run: |
          $ArtifactName = Get-ChildItem -Filter 'OBS-Studio-*-Win-x86+x64.zip' -File
          Write-Output "::set-output name=artifactName::${ArtifactName}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: obs-win
          path: ${{ steps.artifactName.outputs.artifactName }}
      