name: CI
on:
  push:
    branches: [ping-main, Soundwave/dev]
# Environment variables must be single quote delimitted; other scripts read out of this file (very cursed) and expect it.
env:
  DEPS_VERSION_WIN: '2022-03-16'
  VLC_VERSION_WIN: '3.0.0-git'
  CEF_BUILD_VERSION_WIN: '4638'
  CMAKE_GENERATOR: 'Visual Studio 17 2022'
  VIRTUALCAM-GUID: '1B4706D6-9902-454A-8345-32F305BCFD28'
jobs:
  build:
    name: Build
    runs-on: windows-2022
    defaults:
      run:
        working-directory: obs-studio
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: obs-studio
          fetch-depth: 0
          submodules: recursive
      - name: Build
        run: |
          CI/build-windows.ps1 -BuildArch ${{matrix.arch}} -Package
      - name: 'Find artifacts'
        id: findArtifacts
        run: |
          $ArtifactName = (Get-ChildItem -Filter 'OBS-Studio-*-Win-${{matrix.arch}}.zip')
          Write-Output "::set-output name=artifactName::$ArtifactName"
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: 'win-${{matrix.arch}}'
          path: ${{steps.findArtifacts.outputs.artifactName}}
  package:
    name: Package
    runs-on: windows-2022
    needs: build
    steps:
      - name: 'Download 32-bit artifact'
        uses: actions/download-artifact@v3
        with:
          name: win-x86
      - name: 'Download 64-bit artifact'
        uses: actions/download-artifact@v3
        with:
          name: win-x64
      - name: 'Unpack artifacts'
        run: |
          Expand-Archive -Path (Get-ChildItem -Filter 'OBS-Studio-*-Win-x86.zip') -DestinationPath x86
          Expand-Archive -Path (Get-ChildItem -Filter 'OBS-Studio-*-Win-x64.zip') -DestinationPath x64
      - name: 'Repack artifacts'
        run: |
          Copy-Item -Path '.\x86\data\obs-plugins\win-dshow\obs-virtualcam-module32.dll' -Destination '.\x64\data\obs-plugins\win-dshow'
          If (Test-Path '.\x86\data\obs-plugins\win-dshow\obs-virtualcam-module32.pdb') {
            Copy-Item -Path '.\x86\data\obs-plugins\win-dshow\obs-virtualcam-module32.pdb' -Destination '.\x64\data\obs-plugins\win-dshow'
          }
          Copy-Item -Path '.\x64\data\obs-plugins\win-dshow\obs-virtualcam-module64.dll' -Destination '.\x86\data\obs-plugins\win-dshow'
          If (Test-Path '.\x64\data\obs-plugins\win-dshow\obs-virtualcam-module64.pdb') {
            Copy-Item -Path '.\x64\data\obs-plugins\win-dshow\obs-virtualcam-module64.pdb' -Destination '.\x86\data\obs-plugins\win-dshow'
          }
      - name: 'Upload x86 artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: win-x86-virtualcam
          path: x86
      - name: 'Upload x64 artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: win-x64-virtualcam
          path: x64